server:
  port: 8201

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://onion:123456@localhost:8761/register/eureka/
#      defaultZone: http://localhost:8761/register/eureka/


    private String pollName;
    private Class<? extends DataSource> type;
    private String driverClassName;
    private String url;
    private String username;
    private String password;
    private String jndiName;


spring:
  application:
    name: onion-system
  datasource:
    dynamic:
      datasource:
        base:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/onion-cloud-base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: OnionHikariCP
      primary: base
      p6spy: true



security:
  oauth2:
    resource:
        token-info-uri: http://127.0.0.1:8301/auth/oauth/check_token
        id: ${spring.application.name}
    client:
      client-id: cong
      client-secret: 123456




