server:
  port: 8761
  servlet:
    context-path: /register
eureka:
  instance:
      hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/eureka/

spring:
  application:
    name: onion-register
  security:
    user:
      name: onion
      password: 123456





