server:
  port: 8101

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://onion:123456@localhost:8761/register/eureka/
#      defaultZone: http://localhost:8761/register/eureka/

spring:
  application:
    name: onion-auth
  datasource:
    dynamic:
      datasource:
        base:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/onion-cloud-base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: OnionHikariCP
      primary: base
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null





